# Server config
server:
  port: ${PORT:80}

# Spring config
spring:
  application:
    name: search-service
  logging:
    level:
      org.springframework: WARN
      org.hibernate: WARN
  data:
    elasticsearch:
      cluster-name: "docker-cluster"

initial-import:
  enabled: true


# Eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

# Ribbon config
ribbon:
  eureka:
    enabled: true

