# Server config
server:
  port: ${PORT:80}

# Spring config
spring:
  application:
    name: search-service
  logging:
    level:
      org.springframework: WARN
      org.hibernate: WARN
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 0.0.0.0:9300

  elasticsearch:
    rest:
      uris: https://search-search-test-bucmbzybhlmqfexpwwa76odnra.us-east-1.es.amazonaws.com/:9200

initial-import:
  enabled: true


# Eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

# Ribbon config
ribbon:
  eureka:
    enabled: true

